version: '2'
services:
  mongodata:
    image: mongo:3.4
    volumes:
      - /data/db
    command: --break-mongo

  mongo:
    image: mongo:3.4
    volumes_from:
      - mongodata
    ports:
      - "27017:27017"
    command: --smallfiles --rest

  api:
    build:
      context: .
    command: yarn run dev
    volumes:
      - .:/api
    ports:
      - "8080:8080"
    links:
      - mongo
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/controle_frotas
